### ISSUE TITLE
Hoàn thành đồ án

### ISSUE THREAD

**Issue by thaondc** [Dero055/LT-KHDL#2]
Chào mọi người, hiện tại mình đã hoàn thành xong đồ án. Mình mong mọi người sẽ góp ý giùm mình để đồ án trở nên hoàn thiện hơn.
Mình cảm ơn.

**Comment by thaondc** [comment]
Lúc mình up bài lên github, không hiểu tại sao các đồ thị mình vẽ bằng thư viện Plotly không hiển thị. Bạn có thể download file .ipynb hoặc xem trên colab hộ mình.

**Comment by NguyenThaiVu** [comment]
Mình là người góp ý chính: Nguyễn Thái Vũ - 1712921. Mình có 1 số góp ý: 
- Mục đích thực hiện đồ án là tìm ra lời giải đáp cho câu hỏi: "Có mối quan hệ nào tồn tại giữa việc sử dụng rượu bia và kết quả học tập hay không?". Tuy nhiên câu hỏi số 1 của bạn là: "Có sự khác biệt giữa những sinh viên học ban tự nhiên (lớp toán) so với ban xã hội (lớp Tây Ban Nha) không?" điều này có vẻ cần suy nghĩ thêm !
- Về các biểu đồ, mình góp ý bạn nên để thêm tiêu đề, chú thích rõ ràng hơn, để người đọc nhìn vào sẽ dễ hiểu hơn.
- Về phần kết luận, theo như thầy dặn dò các kết luận của bài làm nên được suy ra từ dữ liệu, không được dù trực giác hay suy đoán. VD: ở cuối câu hỏi 4 bạn có kết luận: "Rõ ràng, mọi người thường sử dụng rượu bia bên ngoài hay khi gặp bạn bè. " hoặc "Đối với các gia đình không hạnh phúc, thì vấn đề tâm lý của học sinh sẽ vô cùng áp lực, do đó họ sẽ có xu hướng sử dụng rượu bia để giải tỏa tâm lý." mình chưa thấy dữ liệu làm sáng tỏ những kết luận này.

**Comment by thaondc** [comment]
Chào Vũ,
Đầu tiên, mình xin cảm ơn bạn đã xem hộ bài mình và góp ý giúp mình.
> Mình là người góp ý chính: Nguyễn Thái Vũ - 1712921. Mình có 1 số góp ý:
> 
Về ý đầu tiên, ban đầu, mình chỉ nghĩ đến việc tìm ra mối quan hệ giữa việc uống rượu bia và kết quả học tâp. Nhưng sau này khi làm bài, mình đã mở rộng vấn đề ra. Bởi vì tập dữ liệu còn những thuộc tính khác mà chỉ tập trung một vấn đề này thì "phí" dữ liệu. Mình sẽ sửa lại phần: Mục đích thực hiện đồ án. 
> * Mục đích thực hiện đồ án là tìm ra lời giải đáp cho câu hỏi: "Có mối quan hệ nào tồn tại giữa việc sử dụng rượu bia và kết quả học tập hay không?". Tuy nhiên câu hỏi số 1 của bạn là: "Có sự khác biệt giữa những sinh viên học ban tự nhiên (lớp toán) so với ban xã hội (lớp Tây Ban Nha) không?" điều này có vẻ cần suy nghĩ thêm !

Về hai ý còn lại, mình sẽ chỉnh sửa lại biểu đồ cho hợp lý. Phần đưa ra kết luận, do ban đầu mình chỉ nghĩ là sẽ giải thích những kết quả thống kê được có hợp lý thực tế hay không? Mình sẽ sửa lại để tránh bị sai lầm về quan hệ "nhân quả".
> * Về các biểu đồ, mình góp ý bạn nên để thêm tiêu đề, chú thích rõ ràng hơn, để người đọc nhìn vào sẽ dễ hiểu hơn.
> * Về phần kết luận, theo như thầy dặn dò các kết luận của bài làm nên được suy ra từ dữ liệu, không được dù trực giác hay suy đoán. VD: ở cuối câu hỏi 4 bạn có kết luận: "Rõ ràng, mọi người thường sử dụng rượu bia bên ngoài hay khi gặp bạn bè. " hoặc "Đối với các gia đình không hạnh phúc, thì vấn đề tâm lý của học sinh sẽ vô cùng áp lực, do đó họ sẽ có xu hướng sử dụng rượu bia để giải tỏa tâm lý." mình chưa thấy dữ liệu làm sáng tỏ những kết luận này.

Cảm ơn bạn rất nhiều. =)))
